Задание 12 - Хранение заявок в файле
esButakova/qa-automation-java pull request #12
Opened 2021-09-17 10:23 UTC by esButakova

+ Исправлены методы обновления и поиска заявок

2021-09-18 07:43 UTC, yuri-kudryavtsev requested changes
Привет! 
Молодец, ты хорошо справилась с заданием - сделала сохранение и загрузку из файла с помощью библиотеки Jackson 👍 
Однако, у меня возникло несколько вопросов, почему ты решила реализовать хранение именно таким образом - посмотри плз и отпишись.

2021-09-18 07:43 UTC, yuri-kudryavtsev commented on src/main/java/com/tinkoff/edu/app/repository/VariableLoanCalcRepository.java
> +        List<String> stringsToSave = loans.values().stream()
А для чего ты преобразуешь Map в список? В интернете полно примеров, как сохранить Map в виде json-а с помощью Jackson.

2021-09-18 07:43 UTC, yuri-kudryavtsev commented on src/main/java/com/tinkoff/edu/app/repository/VariableLoanCalcRepository.java
> +    private List<LoanResponse> getResponsesFromFile() {
Можно сразу загружать из файла в Map.

2021-09-18 07:43 UTC, yuri-kudryavtsev commented on src/main/java/com/tinkoff/edu/app/repository/VariableLoanCalcRepository.java
> +        final LoanResponse[] result = {null};
Выглядит очень костыльно и совершенно не ясно, для чего final тут и инициализация списка с пустым элементом.

2021-09-18 07:43 UTC, yuri-kudryavtsev commented on src/main/java/com/tinkoff/edu/app/repository/VariableLoanCalcRepository.java
> +                .ifPresent(response -> result[0] = response);
для чего result[0] = response ? зачем список, когда мы ищем всего лишь один элемент?
Он может быть, а может быть = null.

2021-09-18 07:43 UTC, yuri-kudryavtsev commented on pom.xml
> +            <artifactId>lombok</artifactId>
Для чего тянем lombok? Его использование действительно оправдано для нашего небольшого проекта?

2021-09-19 19:10 UTC, esButakova commented on pom.xml
> +            <artifactId>lombok</artifactId>
Чтобы упростить работу с выбрасываемыми исключениями с помощью SneakyThrows

2021-09-19 19:32 UTC, esButakova commented on src/main/java/com/tinkoff/edu/app/repository/VariableLoanCalcRepository.java
> +        final LoanResponse[] result = {null};
Поиск осущесвтвляется через stream().findFirst(), который возвращает Optional<LoanResponse>. Чтобы вытащить сам LoanResponse и отдать его наружу, используется метод ifPresent().
Метод get() не подойдет, т.к. если поиск ничего не вернет, то выбросится исключение Java.util.NoSuchElementException.
Можно было бы отдавать сразу результат findFirst(), но тогда придется переделывать контракт --> много кода под переделку.
final массив из одного элемента связан с тем, что мы не можем внутри ifPresent() изменять переменную, объявленную выше, а содержимое по ссылке с этой переменной - можем (idea сама подсказывает этот вариант реализации). Поэтому одноэлементный массив - ибо массив не изменяется, а содержимое массива мы изменяем без проблем. 
Почему final - так мы гарантируем, что переменная не изменится.

2021-09-19 19:34 UTC, esButakova commented on src/main/java/com/tinkoff/edu/app/repository/VariableLoanCalcRepository.java
> +                .ifPresent(response -> result[0] = response);
findFirst() всегда возвращает Optional, даже если ничего не найдено. Чтобы вернуть null, нужно развернуть полученный Optional. Детали - в предыдущем комменте.

2021-09-19 19:36 UTC, esButakova commented on src/main/java/com/tinkoff/edu/app/repository/VariableLoanCalcRepository.java
> +        List<String> stringsToSave = loans.values().stream()
И это один из примеров :) Который оказалось проще всего реализовать и он заработал.

2021-09-19 19:45 UTC, esButakova commented on src/main/java/com/tinkoff/edu/app/repository/VariableLoanCalcRepository.java
> +    private List<LoanResponse> getResponsesFromFile() {
В лекции преподаватель показывал варианты работы именно со строками и в условиях задачи не было требования читать файл в Map.
Можно сделать и через Map, но если в файле окажутся дублирующие записи, мы их потеряем, а так вернем все.

2021-09-24 08:42 UTC, yuri-kudryavtsev approved these changes
Привет!
Отличная работа, молодец 👍 

На будущее - постарайся не присваивать статическим переменным значения, которые сложно/долго вычисляются (например чтение содержимого файла). Чем больше таких переменных - тем медленнее запускается программа + есть вероятность, что одна из статических переменных не будет вычислена и тогда весь класс не будет загружен ClassLoader-ом, а это порождает множество всяких непонятных ошибок. Лучше делать такие операции по первому запросу (шаблон проектирования - ленивая инициализация) - изначально переменная = null, при обращении к геттеру проверяем, пустое ли поле, если поле пустое - читаем файл и обновляем поле.

2021-09-24 08:42 UTC, merged